site_name: Gestión de Bases de Datos
site_url: https://cizacas.github.io/GBD26-27-Apuntes/
theme:
  name: material
  language: es
  
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - attr_list
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
  - 'https://unpkg.com/mermaid@11/mermaid.min.js'
  - javascript/mermaid.js
nav:
  - 'Introducción': 'index.md'
  - 'Unidad 1: Sistemas de Almacenamiento de la información': 'UD1_Sistemas_de_alamacenamiento_de_la_informacion.md'